### PR TITLE
Issue-79: Last run updated on error

### LINKED ISSUE #79: Last run updated on error
### Description of the bug

When a feed runs and encounters an error (such as when the remote source is unavailable), the system currently updates the feed's last run time even though the run was unsuccessful. 

### Steps To Reproduce

Configure a feed in a way that it will fail (bad url, etc)
Run the feed
Check the last run time

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by mogmarsh**
## Summary

Fixes #79

## Description

This pull request addresses an issue where the system would update a feed's last run time even when the feed run failed due to errors (such as when the remote source is unavailable). With this fix, the last run time will now only be updated if the feed run is successful. The implementation introduces a boolean parameter to the `after_run()` method to explicitly indicate success or failure, updating the last run timestamp only on successful runs. All relevant method calls have been updated to reflect this logic.

Additionally, the plugin version has been incremented from 1.1.1 to 1.1.2, and the change is documented in `CHANGELOG.md`.

## Steps to Reproduce

1. Configure a feed in a way that it will fail (e.g., use a bad URL).
2. Run the feed.
3. Check the last run time to confirm it is only updated upon successful runs.

## Changelog

- Only update a feed's last run time after a successful run.
- Bump plugin version to 1.1.2.

## Additional Notes

N/A

### CODE REVIEW

File: src/class-runner.php [hunk 1]
```diff
@@ -278,15 +278,19 @@ public function run(): void {
...
 	/**
 	 * Actions to perform after the feed has run.
+	 *
+	 * @param bool $successful Whether the run was successful.
 	 */
-	protected function after_run(): void {
-		// Update the last run time of the feed.
-		update_post_meta( $this->feed_id, static::LAST_RUN_META_KEY, current_time( 'timestamp' ) ); // phpcs:ignore WordPress.DateTime.CurrentTimeTimestamp.Requested
+	protected function after_run( bool $successful ): void {
+		if ( $successful ) {
```
Comment (mboynes) [inline src/class-runner.php:302]: I'm not confident about this approach. While it works for our use case, thinking about more generic usage, it is too narrow and limiting. I'm not 100% on what the right path is, should we store more meta? Should we fire an action? Should we filter how FC responds to an unsuccessful feed? All of the above? I'll summarize my thoughts and maybe it will help direct us...

1. It's useful/important to know when the feed last ran, regardless of its conclusion, so I think we actually should store this regardless.
2. In many cases, it's probably helpful to know (explicitly or implicitly) if the feed that ran was successful or not.
3. How a codebase responds to an unsuccessful feed execution will probably vary. In our client's use case, we're using the timestamp as data in the next run. Maybe if we fired an action here then our custom code could store meta? Or again, maybe this should store additional meta by default, `feed_consumer_last_success_time` or something.

After rubber ducking this, I'm inclined to say that we should store the last success time as another meta entry _and_ fire an action (e.g. `do_action( 'feed_consumer_feed_termination`, $this->feed_id, $successful, $timestamp )`). Then in our client's codebase, we should use the last success time if it's present, the last run time if it's not, and we should `ai_logger()` an error when a feed termination is not successful. What do you think?

File: src/class-runner.php [hunk 2]
```diff
@@ -278,15 +278,19 @@ public function run(): void {
...
+			// Update the last run time of the feed.
+			update_post_meta( $this->feed_id, static::LAST_RUN_META_KEY, current_time( 'timestamp' ) ); // phpcs:ignore WordPress.DateTime.CurrentTimeTimestamp.Requested
```
Comment (mboynes) [inline src/class-runner.php]: ugh, I thought we got rid of all the instances of `current_time( 'timestamp' )`?

**Review by mboynes — CHANGES_REQUESTED** [review]
I wrote far more in my comment than the actual code changes 😆. Ping me after you made updates and I'll re-review!

File: src/class-runner.php (hunk 2 above)
Comment (mogmarsh) [reply src/class-runner.php]: @mboynes I got rid of a few... this one seemed to make sense to keep, because changing the format we're storing in meta between versions could be a breaking change.
https://github.com/alleyinteractive/feed-consumer/pull/78/files

Comment (mboynes) [reply src/class-runner.php]: I think we should rip that bandaid off

File: src/class-runner.php [hunk 3]
```diff
@@ -287,11 +294,25 @@ public function run(): void {
 	 * @param bool $successful Whether the run was successful.
 	 */
 	protected function after_run( bool $successful ): void {
+		// Update the last run time of the feed.
```
Comment (mboynes) [inline src/class-runner.php:297]: Store the timestamp in a variable here `$timestamp = time();` or else the 3 calls could theoretically be different.

(Even though it's a breaking change... so give the version at least a 'minor' bump)

**Review by mboynes — APPROVED** [review]

**Review by mboynes — APPROVED** [review]
💯
