### PR TITLE
Ensure attachments are linked to the parent post

### LINKED ISSUE #51: Ingested images aren't attached to the post
### Description of the bug

When an RSS item with an inline image is ingested, the image is downloaded to the media library but is not attached to the resulting post. It would be great if the image was attached to the article it was ingested from.

### Steps To Reproduce

- Ingest an RSS item with an inline image in the content.
- Visit the media library and note that the image shows as unattached.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by srtfisher**
Fixes #51

### CODE REVIEW

File: src/loader/class-post-loader.php [hunk 1]
```diff
@@ -182,17 +189,41 @@ function ( array $postarr ) use ( $loader_settings ) {
 									return null;
 								}
 
+								$this->listen_for_attachment_creation();
+
+								// Ensure 'post_content' is a string. This is more than
+								// likely a "Block_Converter" instance. Converting is
```
Comment (mogmarsh) [inline src/loader/class-post-loader.php]:
```suggestion
								// likely a "Block_Converter" instance. Converting this
```
This is my best guess of what you meant.

**Review by mogmarsh — APPROVED** [review]
one typo, otherwise 👍
